version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/react'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'bump(react-cortex)'

  - package-ecosystem: 'npm'
    directory: '/packages/core'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'bump(cortex)'

  - package-ecosystem: 'npm'
    directory: '/packages/doc'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'bump(doc)'
