version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/react'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[React Workspace]'

  - package-ecosystem: 'npm'
    directory: '/packages/core'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[Core Workspace]'

  - package-ecosystem: 'npm'
    directory: '/packages/remote-debugger-server'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[Remote Debugger Server Workspace]'

  - package-ecosystem: 'npm'
    directory: '/packages/doc'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[Doc Workspace]'
