name: check workflow

on:
  pull_request:
    branches:
      - main
      - rc

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-dependencies.outputs.cache-key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Get yarn.lock hash
        id: get-hash
        run: echo "LOCKFILE_HASH=${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_ENV

      - name: Display yarn.lock hash
        run: echo "Yarn.lock hash $LOCKFILE_HASH"

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --immutable

  test-core:
    name: Run Core tests
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Use Cached Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run Core tests
        run: yarn workspace @azot-dev/cortex test

      - name: Test Types
        run: yarn workspace @azot-dev/cortex build

  build-doc:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Use Cached Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Check mdx
        run: yarn workspace doc check-mdx

      - name: Build
        run: yarn workspace doc build
