name: Dependency Upgrade

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Upgrade Dependencies
        run: npx npm-check-updates -u && npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore: update dependencies'
          title: 'Update Dependencies'
          body: 'This PR updates npm dependencies'
          branch: 'feature/update-dependencies'
          delete-branch: true
