name: dependabot auto-merge

on:
  pull_request_target:
    types: [opened, edited, synchronize, ready_for_review, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve (major/minor/patch)
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' || steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        uses: peter-evans/approve-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          review-message: Auto-approved Dependabot ${{ steps.metadata.outputs.dependency-names }} (${{ steps.metadata.outputs.update-type }})

      - name: Enable auto-merge for major/minor/patch updates
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' || steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

