name: Combined Workflow

on:
  push:
    branches:
      - main

jobs:
  release-core:
    name: NPM release for core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies for core
        run: |
          cd core
          yarn install --frozen-lockfile

      - name: Release core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd core
          npx semantic-release

  update-react-dep:
    needs: release-core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update peer dependency version
        run: |
          CORTEX_VERSION=$(jq -r ".version" core/package.json)
          jq '.peerDependencies["@azot-dev/cortex"] = "'"$CORTEX_VERSION"'"' react/package.json > react/package.temp.json
          mv react/package.temp.json react/package.json

      - name: Commit and push if changed
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'githubactions@example.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update peerDependency to match local cortex version"
          git pull --rebase origin main
          git push

  release-react:
    needs: update-react-dep
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes
        run: git pull --rebase origin main

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies for react
        run: |
          cd react
          yarn install --frozen-lockfile

      - name: Release react
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd react
          npx semantic-release
