name: semantic release and update peer dependency

on:
  push:
    branches:
      - main

jobs:
  release-and-update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure all tags and branches are fetched

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies
      - run: npm ci

      # Update peer dependency version
      - name: Install jq
        run: sudo apt-get install jq

      - name: Update peer dependency version
        run: |
          # Get the version of cortex from core/package.json
          CORTEX_VERSION=$(jq -r ".version" core/package.json)
          jq '.peerDependencies["'"@azot.dev/cortex"'"] = "'"$CORTEX_VERSION"'"' react/package.json > react/package.temp.json
          mv react/package.temp.json react/package.json

      # Commit and push if changed
      - name: Commit and push if changed
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'githubactions@example.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update peerDependency to match local cortex version"
          git push

      # Run semantic release
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
