name: Release and Update peerDependency

on:
  push:
    branches:
      - main

jobs:
  release-core:
    name: NPM release for core
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies for core
        run: |
          cd core
          yarn install --frozen-lockfile

      - name: Release core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd core
          git pull --rebase
          npx semantic-release

  release-react:
    name: NPM release for react
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Pull latest changes
        run: git pull origin main

      - name: Install Dependencies for react
        run: |
          cd react
          yarn install --frozen-lockfile

      - name: Release react
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd react
          npx semantic-release

  update-dep:
    needs: [release-core, release-react]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Pull latest changes
        run: git pull origin main

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update peer dependency version
        run: |
          # Get the version of cortex from core/package.json
          CORTEX_VERSION=$(jq -r ".version" core/package.json)
          jq '.peerDependencies["'"@azot.dev/cortex"'"] = "'"$CORTEX_VERSION"'"' react/package.json > react/package.temp.json
          mv react/package.temp.json react/package.json

      - name: Commit and push if changed
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'githubactions@example.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update peerDependency to match local cortex version"
          git push
