name: Update peerDependency

on:
  push:
    branches:
      - main

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update peer dependency version
        run: |
          # Get the version of cortex from core/package.json
          CORTEX_VERSION=$(jq -r ".version" core/package.json)

          # Update the react-cortex package.json with this version
          jq ".peerDependencies.cortex = \"$CORTEX_VERSION\"" react-cortex/package.json > react-cortex/package.temp.json
          mv react-cortex/package.temp.json react-cortex/package.json

      - name: Commit and push if changed
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'githubactions@example.com'
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update peerDependency to match local cortex version"
          git push
